# Generated by Django 5.0.7 on 2024-08-01 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rating',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/rating_photos/'),
        ),
        migrations.AlterField(
            model_name='rating',
            name='stars',
            field=models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)]),
        ),
    ]
